openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: Deloitte Consulting CTSE

paths:
  /urls:
    post:
      summary: Create a new shortened url
      operationId: createUrls
      tags:
        - urls
      requestBody:
        description: New url
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: New url
                  example: 'https://www.linkedin.com/in/junghwa-park-279129235'
        required: true
      responses:
        '200':
          description: Success response returns shortened url path
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 12521908512095123
                    url: 'https://www.linkedin.com/in/junghwa-park-279129235'
                    path: 'BEoSs56zu'

  /urls/{shortenedPath}:
    get:
      summary: Return original url to redirect
      operationId: getUrl
      tags:
        - urls
      parameters:
        - name: shortenedPath
          in: path
          required: true
          description: The shortened path
          schema:
            type: string
      responses:
        '307':
          description: Success response returns shortened url path
          headers:
            Location:
              schema:
                type: string
              description: Original URL to redirect
              example: 'https://www.linkedin.com/in/junghwa-park-279129235'
